### ISSUE TITLE
Build error in Win10 / PowerShell

### ISSUE THREAD

**Issue by BlueSlug** [fluid-project/trivet#217]
## Describe the bug
When running the npm `start` or `build` scripts, the console reports the following errors:

```powershell
[build:webpack ] ERROR in ./src/assets/scripts/app.js
[build:webpack ] Module build failed (from ./node_modules/babel-loader/lib/index.js):
[build:webpack ] Error: Unknown option: .assumptions. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
```

```powershell
[build:webpack ] ERROR in ./src/assets/scripts/matomo.js
[build:webpack ] Module build failed (from ./node_modules/babel-loader/lib/index.js):
[build:webpack ] Error: Unknown option: .assumptions. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
```

Please see this gist for the full build log including stack trace: https://gist.github.com/BlueSlug/203ed7af5a6ac32b3b329169140cd8a6

### To reproduce
1. Check out the `main` branch
2. Run `npm ci` to install the dependencies (or `npm install` as the Readme suggests, though this modifies `package-lock.json`)
3. Run `npm run build` to run the build script

### Expected behavior
The build should complete without reporting any errors and exit with a code of 0

## Screenshots
Refer to the gist link above for more detail

### Desktop
 - OS: Windows 10 Pro v.20H2
 - PowerShell 5.1.19041.1320
 - Node.js v16.13.2
 - npm 8.3.1
 - Trivet 0.1.0-dev.0

## Additional context or notes
While running `npm start` or `npm run start` will generate this error, the local server seems to work as expected and the site does not have any apparent issues.

**Comment by greatislander** [comment]
Resolved with dependency updates in #219.

**Comment by jobara** [comment]
Looks like this is because [@babel/core is at v7.12.3](https://github.com/fluid-project/trivet/blob/c48302d46a78dafde867fea7b73175c57f84253e/package-lock.json#L278) but [assumptions](https://babeljs.io/docs/en/assumptions) were added to babel v7.13.0

Running `npm ls @babel/core` on the repo returns

```log
├─┬ fluid-lint-all@1.1.4
 │      └─┬ stylelint@13.13.1
 │             └─┬ @stylelint/postcss-css-in-js@0.37.2
 │                    └── @babel/core@7.12.3 
└─┬ laravel-mix@6.0.34
       └── @babel/core@7.16.0 
```

**Comment by jobara** [comment]
@greatislander you beat me too it :)
