### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by gtirloni** [fluid-project/trivet#48]
## Is your feature request related to a problem?
I would like to submit translations for various languages to websites built on 11ty.

## Describe the solution you'd like
Not applicable.

## Describe alternative solutions you've considered
Not applicable.

**Comment by greatislander** [comment]
A few implementation notes:

- Whatever approach we use, we should try to make it compatible with Netlify CMS (see [docs here](https://www.netlifycms.org/docs/beta-features/#i18n-support))
- Here's a tutorial: https://www.webstoemp.com/blog/multilingual-sites-eleventy/
- Here's a starter project which is configured to use [Forestry](https://forestry.io) as the CMS: https://github.com/lea37/eleventy-multilingual/

**Comment by greatislander** [comment]
### Approach

Collections will contain sub-folders for different locales (`multiple_folders` in Netlify CMS parlance).
